apiVersion: v1
kind: Service
metadata:
  name: kotvukai-service
  namespace: default
spec:
  selector:
    app: kotvukai
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
